"""create_27_core_tables

Revision ID: 389fd6296895
Revises:
Create Date: 2026-09-24 15:39:13.382116+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "389fd6296895"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_role")),
        sa.UniqueConstraint("code", name=op.f("uq_app_role_code")),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("username", name=op.f("uq_app_user_username")),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("code", name=op.f("uq_category_code")),
    )
    op.create_table(
        "partner",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_supplier", sa.Boolean(), nullable=False),
        sa.Column("is_customer", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("is_supplier OR is_customer", name=op.f("ck_partner_ck_partner_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partner")),
        sa.UniqueConstraint("code", name=op.f("uq_partner_code")),
    )
    op.create_table(
        "uom",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "decimal_places BETWEEN 0 AND 4", name=op.f("ck_uom_ck_uom_decimal_places")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uom")),
        sa.UniqueConstraint("code", name=op.f("uq_uom_code")),
    )
    op.create_table(
        "warehouse",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse")),
        sa.UniqueConstraint("code", name=op.f("uq_warehouse_code")),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_name", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["app_user.id"], name=op.f("fk_audit_event_actor_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_table(
        "inventory_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("partner_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.Column("posting_payload_hash", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("posted_by", sa.Uuid(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'REVERSAL') = (reversal_of_id IS NOT NULL)",
            name=op.f("ck_inventory_document_ck_doc_reversal_parity"),
        ),
        sa.CheckConstraint(
            "kind IN ('OPENING','RECEIPT','SHIPMENT','TRANSFER','RECLASSIFY','ADJUSTMENT','CUSTOMER_RETURN','SUPPLIER_RETURN','REVERSAL')",
            name=op.f("ck_inventory_document_ck_doc_kind"),
        ),
        sa.CheckConstraint(
            "status <> 'POSTED' OR (posted_at IS NOT NULL AND posted_by IS NOT NULL AND idempotency_key IS NOT NULL AND posting_payload_hash IS NOT NULL)",
            name=op.f("ck_inventory_document_ck_doc_posted_metadata"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','APPROVED','POSTED','CANCELLED')",
            name=op.f("ck_inventory_document_ck_doc_status"),
        ),
        sa.CheckConstraint(
            "reversal_of_id IS NULL OR reversal_of_id <> id",
            name=op.f("ck_inventory_document_ck_doc_reversal_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["app_user.id"],
            name=op.f("fk_inventory_document_approved_by_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_inventory_document_created_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partner.id"], name=op.f("fk_inventory_document_partner_id_partner")
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"], ["app_user.id"], name=op.f("fk_inventory_document_posted_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["inventory_document.id"],
            name=op.f("fk_inventory_document_reversal_of_id_inventory_document"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_inventory_document_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_document")),
        sa.UniqueConstraint("code", name=op.f("uq_inventory_document_code")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_inventory_document_idempotency_key")),
        sa.UniqueConstraint("reversal_of_id", name=op.f("uq_inventory_document_reversal_of_id")),
    )
    op.create_table(
        "location",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("usage", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "usage IN ('STRUCTURAL','STORAGE','RECEIVING','DISPATCH','TRANSIT')",
            name=op.f("ck_location_ck_location_usage"),
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name=op.f("ck_location_ck_location_parent_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id", "warehouse_id"],
            ["location.id", "location.warehouse_id"],
            name="fk_location_parent_same_warehouse",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouse.id"], name=op.f("fk_location_warehouse_id_warehouse")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location")),
        sa.UniqueConstraint("id", "warehouse_id", name="uq_location_id_warehouse"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_location_warehouse_code"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("base_uom_id", sa.Uuid(), nullable=False),
        sa.Column("track_expiry", sa.Boolean(), nullable=False),
        sa.Column("min_shelf_life_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "min_shelf_life_days >= 0", name=op.f("ck_product_ck_product_min_shelf_life_days")
        ),
        sa.ForeignKeyConstraint(
            ["base_uom_id"], ["uom.id"], name=op.f("fk_product_base_uom_id_uom")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name=op.f("fk_product_category_id_category")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("sku", name=op.f("uq_product_sku")),
    )
    op.create_table(
        "purchase_order",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expected_on", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','CONFIRMED','CLOSED','CANCELLED')",
            name=op.f("ck_purchase_order_ck_purchase_order_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_purchase_order_created_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["partner.id"], name=op.f("fk_purchase_order_supplier_id_partner")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_purchase_order_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order")),
        sa.UniqueConstraint("code", name=op.f("uq_purchase_order_code")),
    )
    op.create_table(
        "sales_order",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expected_on", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','CONFIRMED','CLOSED','CANCELLED')",
            name=op.f("ck_sales_order_ck_sales_order_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_sales_order_created_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["partner.id"], name=op.f("fk_sales_order_customer_id_partner")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouse.id"], name=op.f("fk_sales_order_warehouse_id_warehouse")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order")),
        sa.UniqueConstraint("code", name=op.f("uq_sales_order_code")),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["app_role.id"],
            name=op.f("fk_user_role_role_id_app_role"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_role_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_role")),
    )
    op.create_table(
        "lot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("manufacturer_lot_code", sa.String(length=100), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("manufactured_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("recall_status", sa.String(length=20), nullable=False),
        sa.Column("block_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "recall_status IN ('ACTIVE','BLOCKED')", name=op.f("ck_lot_ck_lot_recall_status")
        ),
        sa.CheckConstraint(
            "manufactured_on IS NULL OR expires_on IS NULL OR manufactured_on <= expires_on",
            name=op.f("ck_lot_ck_lot_dates"),
        ),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_lot_ck_lot_unit_cost")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_lot_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["partner.id"], name=op.f("fk_lot_supplier_id_partner")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lot")),
        sa.UniqueConstraint("code", name=op.f("uq_lot_code")),
        sa.UniqueConstraint("id", "product_id", name="uq_lot_id_product"),
    )
    op.create_table(
        "product_uom",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("uom_id", sa.Uuid(), nullable=False),
        sa.Column("factor_to_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint(
            "factor_to_base > 0", name=op.f("ck_product_uom_ck_product_uom_factor_to_base")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_product_uom_product_id_product")
        ),
        sa.ForeignKeyConstraint(["uom_id"], ["uom.id"], name=op.f("fk_product_uom_uom_id_uom")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_uom")),
        sa.UniqueConstraint("id", "product_id", name="uq_product_uom_id_product"),
        sa.UniqueConstraint("product_id", "uom_id", name="uq_product_uom_product_uom"),
    )
    op.create_table(
        "reorder_policy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("min_qty_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reorder_point_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_qty_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint(
            "max_qty_base >= reorder_point_base",
            name=op.f("ck_reorder_policy_ck_reorder_max_point"),
        ),
        sa.CheckConstraint(
            "min_qty_base >= 0", name=op.f("ck_reorder_policy_ck_reorder_min_non_negative")
        ),
        sa.CheckConstraint(
            "reorder_point_base >= min_qty_base",
            name=op.f("ck_reorder_policy_ck_reorder_point_min"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_reorder_policy_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_reorder_policy_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reorder_policy")),
        sa.UniqueConstraint(
            "product_id", "warehouse_id", name="uq_reorder_policy_product_warehouse"
        ),
    )
    op.create_table(
        "stocktake",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("adjustment_document_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','COUNTING','REVIEW','POSTED','CANCELLED')",
            name=op.f("ck_stocktake_ck_stocktake_status"),
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_document_id"],
            ["inventory_document.id"],
            name=op.f("fk_stocktake_adjustment_document_id_inventory_document"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_stocktake_created_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["location.id"], name=op.f("fk_stocktake_location_id_location")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouse.id"], name=op.f("fk_stocktake_warehouse_id_warehouse")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stocktake")),
        sa.UniqueConstraint("code", name=op.f("uq_stocktake_code")),
    )
    op.create_table(
        "supplier_product",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_sku", sa.String(length=100), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("moq_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("order_multiple_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quoted_unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("is_preferred", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_supplier_product_ck_supplier_product_lead_time")
        ),
        sa.CheckConstraint(
            "moq_base >= 0", name=op.f("ck_supplier_product_ck_supplier_product_moq")
        ),
        sa.CheckConstraint(
            "order_multiple_base > 0", name=op.f("ck_supplier_product_ck_supplier_product_multiple")
        ),
        sa.CheckConstraint(
            "quoted_unit_cost IS NULL OR quoted_unit_cost >= 0",
            name=op.f("ck_supplier_product_ck_supplier_product_cost"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_supplier_product_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["partner.id"], name=op.f("fk_supplier_product_supplier_id_partner")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_product")),
        sa.UniqueConstraint("supplier_id", "product_id", name="uq_supplier_product"),
    )
    op.create_table(
        "product_barcode",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("product_uom_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_uom_id"],
            ["product_uom.id"],
            name=op.f("fk_product_barcode_product_uom_id_product_uom"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_barcode")),
        sa.UniqueConstraint("code", name=op.f("uq_product_barcode_code")),
    )
    op.create_table(
        "purchase_order_line",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_uom_id", sa.Uuid(), nullable=False),
        sa.Column("ordered_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("factor_to_base_snapshot", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("closed_qty_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "closed_qty_base <= ordered_qty * factor_to_base_snapshot",
            name=op.f("ck_purchase_order_line_ck_po_closed_qty_max"),
        ),
        sa.CheckConstraint(
            "closed_qty_base >= 0",
            name=op.f("ck_purchase_order_line_ck_po_closed_qty_non_negative"),
        ),
        sa.CheckConstraint(
            "factor_to_base_snapshot > 0", name=op.f("ck_purchase_order_line_ck_po_factor")
        ),
        sa.CheckConstraint("line_no > 0", name=op.f("ck_purchase_order_line_ck_po_line_no")),
        sa.CheckConstraint(
            "ordered_qty > 0", name=op.f("ck_purchase_order_line_ck_po_ordered_qty")
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_purchase_order_line_ck_po_unit_price")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_order.id"],
            name=op.f("fk_purchase_order_line_order_id_purchase_order"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_purchase_order_line_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["product_uom_id", "product_id"],
            ["product_uom.id", "product_uom.product_id"],
            name="fk_po_line_product_uom",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_line")),
        sa.UniqueConstraint("id", "product_id", name="uq_po_line_id_product"),
        sa.UniqueConstraint("order_id", "line_no", name="uq_po_line_no"),
    )
    op.create_table(
        "sales_order_line",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_uom_id", sa.Uuid(), nullable=False),
        sa.Column("ordered_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("factor_to_base_snapshot", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("closed_qty_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "closed_qty_base <= ordered_qty * factor_to_base_snapshot",
            name=op.f("ck_sales_order_line_ck_so_closed_qty_max"),
        ),
        sa.CheckConstraint(
            "closed_qty_base >= 0", name=op.f("ck_sales_order_line_ck_so_closed_qty_non_negative")
        ),
        sa.CheckConstraint(
            "factor_to_base_snapshot > 0", name=op.f("ck_sales_order_line_ck_so_factor")
        ),
        sa.CheckConstraint("line_no > 0", name=op.f("ck_sales_order_line_ck_so_line_no")),
        sa.CheckConstraint("ordered_qty > 0", name=op.f("ck_sales_order_line_ck_so_ordered_qty")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sales_order_line_ck_so_unit_price")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["sales_order.id"],
            name=op.f("fk_sales_order_line_order_id_sales_order"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_sales_order_line_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["product_uom_id", "product_id"],
            ["product_uom.id", "product_uom.product_id"],
            name="fk_so_line_product_uom",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_line")),
        sa.UniqueConstraint("id", "product_id", name="uq_so_line_id_product"),
        sa.UniqueConstraint("order_id", "line_no", name="uq_so_line_no"),
    )
    op.create_table(
        "stock_balance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("on_hand", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reserved", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_stock_balance_ck_stock_balance_condition"),
        ),
        sa.CheckConstraint(
            "on_hand >= 0", name=op.f("ck_stock_balance_ck_stock_balance_on_hand_non_negative")
        ),
        sa.CheckConstraint(
            "reserved <= on_hand", name=op.f("ck_stock_balance_ck_stock_balance_reserved_max")
        ),
        sa.CheckConstraint(
            "reserved >= 0", name=op.f("ck_stock_balance_ck_stock_balance_reserved_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["location.id"], name=op.f("fk_stock_balance_location_id_location")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id", "product_id"], ["lot.id", "lot.product_id"], name="fk_stock_balance_lot"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_stock_balance_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_balance")),
        sa.UniqueConstraint(
            "product_id", "location_id", "lot_id", "condition", name="uq_stock_balance_bucket"
        ),
    )
    op.create_table(
        "stocktake_line",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stocktake_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("snapshot_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("counted_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("difference_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.CheckConstraint(
            "condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_stocktake_line_ck_stocktake_condition"),
        ),
        sa.CheckConstraint(
            "(counted_qty IS NULL) = (difference_qty IS NULL)",
            name=op.f("ck_stocktake_line_ck_stocktake_diff_parity"),
        ),
        sa.CheckConstraint(
            "counted_qty IS NULL OR counted_qty >= 0",
            name=op.f("ck_stocktake_line_ck_stocktake_counted_non_negative"),
        ),
        sa.CheckConstraint(
            "counted_qty IS NULL OR difference_qty = counted_qty - snapshot_qty",
            name=op.f("ck_stocktake_line_ck_stocktake_diff_math"),
        ),
        sa.CheckConstraint(
            "snapshot_qty >= 0", name=op.f("ck_stocktake_line_ck_stocktake_snapshot_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["location.id"], name=op.f("fk_stocktake_line_location_id_location")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id", "product_id"], ["lot.id", "lot.product_id"], name="fk_stocktake_line_lot"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_stocktake_line_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["stocktake_id"],
            ["stocktake.id"],
            name=op.f("fk_stocktake_line_stocktake_id_stocktake"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stocktake_line")),
        sa.UniqueConstraint(
            "stocktake_id",
            "product_id",
            "location_id",
            "lot_id",
            "condition",
            name="uq_stocktake_line_bucket",
        ),
    )
    op.create_table(
        "inventory_document_line",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("product_uom_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("factor_to_base_snapshot", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("qty_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("from_location_id", sa.Uuid(), nullable=True),
        sa.Column("from_condition", sa.String(length=20), nullable=True),
        sa.Column("to_location_id", sa.Uuid(), nullable=True),
        sa.Column("to_condition", sa.String(length=20), nullable=True),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("sales_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("original_line_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "from_condition IS NULL OR from_condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_inventory_document_line_ck_doc_line_from_condition"),
        ),
        sa.CheckConstraint(
            "to_condition IS NULL OR to_condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_inventory_document_line_ck_doc_line_to_condition"),
        ),
        sa.CheckConstraint(
            "(from_location_id IS NULL) = (from_condition IS NULL)",
            name=op.f("ck_inventory_document_line_ck_doc_line_from_loc_cond"),
        ),
        sa.CheckConstraint(
            "(to_location_id IS NULL) = (to_condition IS NULL)",
            name=op.f("ck_inventory_document_line_ck_doc_line_to_loc_cond"),
        ),
        sa.CheckConstraint(
            "NOT (purchase_order_line_id IS NOT NULL AND sales_order_line_id IS NOT NULL)",
            name=op.f("ck_inventory_document_line_ck_doc_line_not_both_po_so"),
        ),
        sa.CheckConstraint(
            "factor_to_base_snapshot > 0",
            name=op.f("ck_inventory_document_line_ck_doc_line_factor"),
        ),
        sa.CheckConstraint(
            "from_location_id IS NOT NULL OR to_location_id IS NOT NULL",
            name=op.f("ck_inventory_document_line_ck_doc_line_has_movement"),
        ),
        sa.CheckConstraint("line_no > 0", name=op.f("ck_inventory_document_line_ck_doc_line_no")),
        sa.CheckConstraint("qty > 0", name=op.f("ck_inventory_document_line_ck_doc_line_qty")),
        sa.CheckConstraint(
            "qty_base = qty * factor_to_base_snapshot",
            name=op.f("ck_inventory_document_line_ck_doc_line_qty_base_math"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["inventory_document.id"],
            name=op.f("fk_inventory_document_line_document_id_inventory_document"),
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["location.id"],
            name=op.f("fk_inventory_document_line_from_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["lot_id", "product_id"], ["lot.id", "lot.product_id"], name="fk_doc_line_lot"
        ),
        sa.ForeignKeyConstraint(
            ["original_line_id"],
            ["inventory_document_line.id"],
            name=op.f("fk_inventory_document_line_original_line_id_inventory_document_line"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_inventory_document_line_product_id_product"),
        ),
        sa.ForeignKeyConstraint(
            ["product_uom_id", "product_id"],
            ["product_uom.id", "product_uom.product_id"],
            name="fk_doc_line_product_uom",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_line.id"],
            name=op.f("fk_inventory_document_line_purchase_order_line_id_purchase_order_line"),
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_line_id"],
            ["sales_order_line.id"],
            name=op.f("fk_inventory_document_line_sales_order_line_id_sales_order_line"),
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["location.id"],
            name=op.f("fk_inventory_document_line_to_location_id_location"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_document_line")),
        sa.UniqueConstraint("document_id", "line_no", name="uq_doc_line_no"),
        sa.UniqueConstraint("id", "product_id", "lot_id", name="uq_doc_line_id_prod_lot"),
    )
    op.create_table(
        "stock_reservation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sales_order_line_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("reserved_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("consumed_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("released_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_stock_reservation_ck_res_condition"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','CONSUMED','RELEASED','EXPIRED')",
            name=op.f("ck_stock_reservation_ck_res_status"),
        ),
        sa.CheckConstraint(
            "consumed_qty + released_qty <= reserved_qty",
            name=op.f("ck_stock_reservation_ck_res_sum_limits"),
        ),
        sa.CheckConstraint(
            "consumed_qty >= 0", name=op.f("ck_stock_reservation_ck_res_consumed_non_negative")
        ),
        sa.CheckConstraint(
            "released_qty >= 0", name=op.f("ck_stock_reservation_ck_res_released_non_negative")
        ),
        sa.CheckConstraint(
            "reserved_qty > 0", name=op.f("ck_stock_reservation_ck_res_qty_positive")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["location.id"], name=op.f("fk_stock_reservation_location_id_location")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id", "product_id"], ["lot.id", "lot.product_id"], name="fk_stock_reservation_lot"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_stock_reservation_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_line_id"],
            ["sales_order_line.id"],
            name=op.f("fk_stock_reservation_sales_order_line_id_sales_order_line"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_reservation")),
    )
    op.create_table(
        "reservation_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document_line_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(event_type = 'CONSUME') = (document_line_id IS NOT NULL)",
            name=op.f("ck_reservation_event_ck_res_event_consume_doc_line"),
        ),
        sa.CheckConstraint(
            "event_type IN ('ALLOCATE','CONSUME','RELEASE','EXPIRE')",
            name=op.f("ck_reservation_event_ck_res_event_type"),
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_reservation_event_ck_res_event_qty")),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["app_user.id"], name=op.f("fk_reservation_event_actor_id_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["document_line_id"],
            ["inventory_document_line.id"],
            name=op.f("fk_reservation_event_document_line_id_inventory_document_line"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["stock_reservation.id"],
            name=op.f("fk_reservation_event_reservation_id_stock_reservation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_event")),
    )
    op.create_table(
        "stock_movement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_line_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("from_location_id", sa.Uuid(), nullable=True),
        sa.Column("from_condition", sa.String(length=20), nullable=True),
        sa.Column("to_location_id", sa.Uuid(), nullable=True),
        sa.Column("to_condition", sa.String(length=20), nullable=True),
        sa.Column("qty_base", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reverses_movement_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "from_condition IS NULL OR from_condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_stock_movement_ck_movement_from_condition"),
        ),
        sa.CheckConstraint(
            "to_condition IS NULL OR to_condition IN ('GOOD','QUARANTINE','DAMAGED')",
            name=op.f("ck_stock_movement_ck_movement_to_condition"),
        ),
        sa.CheckConstraint(
            "(from_location_id IS NULL) = (from_condition IS NULL)",
            name=op.f("ck_stock_movement_ck_movement_from_loc_cond"),
        ),
        sa.CheckConstraint(
            "(to_location_id IS NULL) = (to_condition IS NULL)",
            name=op.f("ck_stock_movement_ck_movement_to_loc_cond"),
        ),
        sa.CheckConstraint(
            "from_location_id IS NOT NULL OR to_location_id IS NOT NULL",
            name=op.f("ck_stock_movement_ck_movement_has_movement"),
        ),
        sa.CheckConstraint("qty_base > 0", name=op.f("ck_stock_movement_ck_movement_qty_base")),
        sa.CheckConstraint(
            "reverses_movement_id IS NULL OR reverses_movement_id <> id",
            name=op.f("ck_stock_movement_ck_movement_not_reverse_self"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["app_user.id"], name=op.f("fk_stock_movement_actor_id_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["document_line_id", "product_id", "lot_id"],
            [
                "inventory_document_line.id",
                "inventory_document_line.product_id",
                "inventory_document_line.lot_id",
            ],
            name="fk_movement_doc_line",
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["location.id"],
            name=op.f("fk_stock_movement_from_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["lot_id", "product_id"], ["lot.id", "lot.product_id"], name="fk_movement_lot"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_stock_movement_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["reverses_movement_id"],
            ["stock_movement.id"],
            name=op.f("fk_stock_movement_reverses_movement_id_stock_movement"),
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["location.id"],
            name=op.f("fk_stock_movement_to_location_id_location"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movement")),
        sa.UniqueConstraint("document_line_id", name=op.f("uq_stock_movement_document_line_id")),
        sa.UniqueConstraint(
            "reverses_movement_id", name=op.f("uq_stock_movement_reverses_movement_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_movement")
    op.drop_table("reservation_event")
    op.drop_table("stock_reservation")
    op.drop_table("inventory_document_line")
    op.drop_table("stocktake_line")
    op.drop_table("stock_balance")
    op.drop_table("sales_order_line")
    op.drop_table("purchase_order_line")
    op.drop_table("product_barcode")
    op.drop_table("supplier_product")
    op.drop_table("stocktake")
    op.drop_table("reorder_policy")
    op.drop_table("product_uom")
    op.drop_table("lot")
    op.drop_table("user_role")
    op.drop_table("sales_order")
    op.drop_table("purchase_order")
    op.drop_table("product")
    op.drop_table("location")
    op.drop_table("inventory_document")
    op.drop_table("audit_event")
    op.drop_table("warehouse")
    op.drop_table("uom")
    op.drop_table("partner")
    op.drop_table("category")
    op.drop_table("app_user")
    op.drop_table("app_role")
    # ### end Alembic commands ###
